name: send mail TUNG
on:
  workflow_dispatch:
jobs:
  run-job:
    runs-on: ubuntu-latest
    container:
      image: d4rkk3y/mbf-auto-env:latest
      options: --user 1001
      env:
        PASSWORD: ${{ secrets.PASSWORD }}
      credentials:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Run task
        run: |
          python encrypt.py --mode dec --input  ./mail.zip.enc --output ./mail.zip --password $PASSWORD
          unzip ./mail.zip
          python main2.py
      - uses: EndBug/add-and-commit@v9
        with:
          add: '["status1.txt", "status2.txt"]'
